context:
  name: box2d
  version: "3.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/erincatto/box2d/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7fac19801485efb31ee3745b2284d9d4601f9e8138a3383a7b0df6d788ea5785
  patches:
    - cmake.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      lib:
        - box2d
      include:
        - box2d/base.h
        - box2d/box2d.h
        - box2d/collision.h
        - box2d/id.h
        - box2d/math_functions.h
        - box2d/types.h

about:
  homepage: https://box2d.org/
  summary: "Box2D is a 2D physics engine for games."
  description: |
    An open source C engine for simulating rigid bodies in 2D, uses the C17 standard.
  license: MIT
  license_file: LICENSE
  documentation: https://box2d.org/documentation/
  repository: https://github.com/erincatto/box2d

extra:
  recipe-maintainers:
    - tdejager
    - baszalmstra
