schema_version: 1

context:
  name: katago
  version: 1.15.3
  cuda: ${{ "true" if cuda_compiler_version != "None" else "false" }}
  cuda_build_string: cuda_${{ cuda_compiler_version | version_to_buildstring }}
  string_prefix: ${{ cuda_build_string if cuda == "true" else "cpu_" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # NOTE: The below block using git as a source is disabled for now, see `source.patches` section.
  # use git_url, because katago needs a git repo to compile BUILD_DISTRIBUTED support;
  # this cannot (or rather: should not) be patch out, or even patched at all (-> dirty tag),
  # compare the exceedingly clear instructions/pleas here:
  # https://github.com/lightvector/KataGo/blob/master/Compiling.md#building-for-distributed
  # git: https://github.com/lightvector/KataGo.git
  # tag: v${{ version }}

  url: https://github.com/lightvector/KataGo/archive/refs/tags/v${{ version }}.zip
  sha256: 8bd0eb1e4d6533cc7ca116e957d86026fb2d3ecf4a57e9974984dbbc4cecd3b3
  patches:
    # Katago is being built with the distributed option enabled, which requires a git repo
    # to be present (see https://github.com/lightvector/KataGo/blob/master/Compiling.md#building-for-distributed).
    # But using a git source with v1 recipe trigger an error (see https://github.com/conda-forge/conda-smithy/issues/2239).
    # In consequence, for now we must stick to using the url as a source. We then apply the below patch in order to adapt the CMake logic to not use `git`.
    # Important: for every update, you must update the patch to match sha256sum for this version.
    # Related feedstock tickets:
    # - https://github.com/conda-forge/katago-feedstock/pull/13
    # - https://github.com/conda-forge/katago-feedstock/pull/11
    - no-git.patch

build:
  number: 0
  skip:
    # - cuda == "true" and win
    - cuda == "true" and match(cuda_compiler_version, "<12")
  string: ${{ string_prefix }}h${{ hash }}_${{ build_number }}
  variant:
    use_keys:
      # use cuda from the variant config, e.g. to build multiple CUDA variants
      - ${{ "cuda" if cuda == "true" }}
    # this will down-prioritize the cuda variant versus other variants of the package
    down_prioritize_variant: ${{ 1 if cuda == "true" else 0 }}

requirements:
  build:
    - if: cuda == "true"
      then:
        - ${{ compiler('cuda') }}

    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - curl
    # - git  # not needed at the moment, see `source.patches`` section
  host:
    - if: cuda == "true"
      then:
        - cuda-version ==${{ cuda_compiler_version }}
        - libcublas-dev
        - cudnn
        - ${{ "nccl" if linux }}

    # libraries
    - zlib
    - libzip
    - eigen
    # necessary for BUILD_DISTRIBUTED
    - openssl

tests:
  - files:
      source:
        - cpp/tests/
    script:
      - katago
      - katago version

      # fails some accuracy tests on osx
      - ${{ "katago runtests" if not osx }}
      - ${{ "katago runnnlayertests" if cuda != "true" }}

      # run some tests that hopefully exercise the distributed code a bit as well
      # (based on searching "distributed" under cpp/tests and running the right portion)

      - if: unix
        then:
          - cd cpp/
          - mkdir tests/scratch
          - katago runoutputtests
          - ${{ "katago runtinynntests tests/scratch 1.0" if cuda != "true" }}

      - if: win
        then:
          - cd cpp/
          - mkdir tests\scratch
          - - ${{ "katago runtinynntests tests/scratch 1.0" if cuda != "true" }}

about:
  summary: GTP engine and self-play learning in Go
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/lightvector/KataGo

extra:
  recipe-maintainers:
    - hadim
