context:
  version: "0.3.0"
  build_number: 0

recipe:
  name: torchcodec-split
  version: ${{ version }}

source:
  - url: https://github.com/pytorch/torchcodec/archive/refs/tags/v${{ version }}.tar.gz
    sha256: f535f184f7abe2460d759df7157fa99b40a12ee5d6ffc2eb9155956b7cc209d8
    patches:
      - use_strict_threshold_only_for_linux_x86_64.patch
      - 657.patch
      - remove_werror.patch

outputs:
  - package:
      name: torchcodec

about:
  homepage: https://github.com/pytorch/torchcodec
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: TorchCodec is a Python library for decoding videos into PyTorch tensors, on CPU and CUDA GPU.

extra:
  recipe-maintainers:
    - traversaro
  feedstock-name: torchcodec
