schema_version: 1

context:
  name: python-gfal2
  version: 1.13.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gitlab.cern.ch/dmc/gfal2-bindings/-/archive/v${{ version }}/gfal2-bindings-v${{ version }}.tar.gz
  sha256: 187ef74043726ca1cd96e233689616b691952063ed54653cfece02a974b14c95
  patches:
    - 0001-Force-CMake-to-use-the-correct-Python.patch

build:
  number: 0
  skip: win
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - gfal2
    - libboost-python-devel
    - glib
  run:
    - python

tests:
  - python:
      imports:
        - gfal2
      pip_check: false

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: GFAL (Grid File Access Library) is a C library providing an abstraction layer of the grid storage system complexity.
  description: |
    GFAL (Grid File Access Library) is a C library providing an abstraction
    layer of the grid storage system complexity. The version 2 of GFAL tries to
    simplify at the maximum the file operations in a distributed environment.
    The complexity of the grid is hidden from the client side behind a simple
    common POSIX API. GFAL2 is able to manage all the common used file access
    protocols in a grid & cloud environment.
  homepage: https://dmc-docs.web.cern.ch/dmc-docs/
  repository: https://gitlab.cern.ch/dmc/gfal2-bindings
  documentation: https://dmc-docs.web.cern.ch/dmc-docs/gfal2-python.html

extra:
  recipe-maintainers:
    - chrisburr
