schema_version: 1

context:
  name: dismod-at
  version: 2025.4.16

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  #
  url: https://github.com/bradbell/dismod_at/archive/${{ version }}.tar.gz
  sha256: 0237d219817057d51a12f6e4902ffc0a176ca8b46d2b6f2f4adf166c5cd1c395
  #
  patches:
    # rattler-build does not support scripts in pyproject.toml.
    # This patch removes the following code from python/pyproject.toml
    # [project.scripts]
    # dismod-at = 'dismod_at:main'
    - ${{ version }}.patch

build:
  # second build on this version
  number: 2
  #
  # rattler-build does not handle python install scripts properly.
  python:
    # This creates the script that was removed by the patch file above
    # (in a way that works when using rattler-build).
    entry_points:
      - dismod-at = dismod_at:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - pkg-config
    - cppad-mixed
    - sqlite
    - eigen
    - numpy
    - matplotlib-base
    - scipy
  run:
    - python
    - numpy
    - matplotlib-base
    - scipy
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - script:
      interpreter: python
      file: run_test.py
    requirements:
      run:
        - python
        - numpy
        - matplotlib
        - scipy
        - sqlite
    files:
      source:
        # see test_file at top of run_test.py
        - example/get_started/get_started_db.py
        - example/get_started/fit_command.py
        - test/user/db2csv.py

about:
  license: AGPL-3.0-or-later
  license_file: agpl-3.0.txt
  summary: Estimating disease rates as functions of age and time.
  homepage: https://dismod-at.readthedocs.io/stable-2025
  repository: https://github.com/bradbell/dismod_at
  documentation: https://dismod-at.readthedocs.io/stable-2025/

extra:
  recipe-maintainers:
    - bradbell
